### ISSUE TITLE
Package download statistics are not updated

### ISSUE THREAD

**Issue by volkanceylan** [NuGet/NuGetGallery#2329]
For last three days package download counts on nuget.org are not increased.

Main page is always showing 280,266,060 package downloads and it stayed constant since 2014-11-08. Some packages i use (e.g. Serenity.Web 1.4.0) shows 0 download count.

**Comment by ChrisSfanos** [comment]
We are looking to improve the mechanism for stats - adding this for future work

**Comment by RanjiniM** [comment]
This issue should be fixed now.

**Comment by ttutisani** [comment]
It seems count is frozen for my nuget package (https://www.nuget.org/packages/Xunit.Gherkin.Quick/) for the last week.
I'm fine with thinking that there are no new downloads, but I believe there must be.
Has anybody else complained about the same recently? Or is it just me?

**Comment by gurmitteotia** [comment]
I can see similar issue with my package https://www.nuget.org/packages/Guflow/1.0.68.  I did a test and downloaded the package version 1.0.68  from 4-5 different machines today but it did not have any impact on downloaded counts even after 4-5 hours. It is frozen.

**Comment by ttutisani** [comment]
This is still happening and has happened several times repeatedly and intermittently.

**Comment by sheryever** [comment]
I am also facing the same issue 
(https://www.nuget.org/packages/SimpleAccess.SqlServer)

**Comment by zHaytam** [comment]
Same thing for my package: https://www.nuget.org/stats/packages/Z.Blazor.Diagrams
The statistics page says that no stats are currently available, even the NuGet search / Visual Studio package manage shows 0, but when you go into the package, it says it has downloads (77?).
