### ISSUE TITLE
Production issue: download count = 0 for new packages (after 25 march)

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#2962]
There seems a problem with the download count. It's visible with new packages, but probably it's also we older packages. 

We installed NLog 4.30-rc2 , but the download stays 0. 
- https://www.nuget.org/packages/NLog/

![image](https://cloud.githubusercontent.com/assets/5808377/14139693/deea6b3c-f674-11e5-8dfa-9888e81deeb0.png)

We see also in other new recent packages that the download count stays 0.

- https://www.nuget.org/packages/Plot.Testing/0.1.20
![image](https://cloud.githubusercontent.com/assets/5808377/14139731/05c63d9e-f675-11e5-80ca-e965320d1d44.png)

- https://www.nuget.org/packages/AMS/1.0.5933.1549
![image](https://cloud.githubusercontent.com/assets/5808377/14139745/1c8c67f6-f675-11e5-97e3-c6b089cce35a.png)

- https://www.nuget.org/packages/Paket/2.56.6
![image](https://cloud.githubusercontent.com/assets/5808377/14139752/29ef071e-f675-11e5-8164-4ccbae7a1031.png)

and others:

- https://www.nuget.org/packages/LibLog/4.2.5
- https://www.nuget.org/packages/LanguageExt.Process/1.7.32
- https://www.nuget.org/packages/LanguageExt.Core/
- https://www.nuget.org/packages/autofixture/

It looks like there are no download stats after 25 march

**Comment by maartenba** [comment]
This has been resolved as mentioned on http://status.nuget.org

**Comment by 304NotModified** [comment]
thanks! I checked the status pagina on 27/28 march

**Comment by maartenba** [comment]
We only posted yesterday so that's correct :) Thanks for letting us know about this though!

**Comment by 304NotModified** [comment]
This issue is closed but it's still an issue? 

It would be nice to know when this is fixed.

**Comment by maartenba** [comment]
We are performing data rollups, with stats lagging a bit. We have the data, it just takes a while for it to show up.

**Comment by xavierdecoster** [comment]
Some context: We can't do rollups and generate fresh stats at the same time. We're rolling up a huge amount of data into a fraction of its current storage space, which causes quite a bit of index fragmentation. This one-time process currently continues over the weekend and may take a few more days after that. Once completed, a much smaller data rollup will happen on a regular basis, which should no longer affect stats generation this much. We'll interrupt the data rollups again this Monday to generate fresh stats. These daily interruptions prolong the whole data rollup process quite a bit though, so please hang in there and enjoy the weekend☺

**Comment by 304NotModified** [comment]
Thanks for the replies.  It's clear to me why is not up to date and that the data is present. 

But what isn't clear: is the (big)  stats lag a fact we have to live with? Or is it resolved some day? 

I don't want to post a message every time the stats are out to date and this is a known issue at your site.  But I was under the impression that the stats lag was solved 18 days ago. After that, there was a lag at least 2 times which surprised me.

**Comment by maartenba** [comment]
See above reply from @xavierdecoster. The lag is caused by having to stop processing for maintenance. We stop maintenance regularly to have stats catch up. Eventually when we complete maintenance stats will be up to date (note there has always been a ~6hr delay and that will remain after maintenance)

**Comment by 304NotModified** [comment]
Hi @maartenba ,

There is only one thing which isn't clear to me: is this long lag (more than 12 hours), recurring behavior? 

This issue was closed and I was under the impression it was an exception and it was solved, but as far as I now understand it's a "known issue" and nothing to do about it. Am I correct?

**Comment by maartenba** [comment]
The 12 hrs is when we run maintenance (ongoing and catching up every few hours). Will go away when done with maintenance (so yes, known issue / intentional issue ☺ )
