### ISSUE TITLE
Custom Nuget Gallery Display Packages Not working

### ISSUE THREAD

**Issue by tharunr184** [NuGet/NuGetGallery#7126]
Hello, We internally host NuGet Gallery on IIS. I tried to update the gallery and build the solution and ran update-database command to upgrade the database schema. We deployed the latest code in IIS and everything works fine, except I am not able to see old packages. We store our old packages in File system and added a virtual directory in App_data directory to point to the packages location. I can access the packages by URL(Ex: https://localhost/packages/packagename). However when I try to access https://locahost/packages I don't see any packages. Please advise?

**Comment by tharunr184** [comment]
Hey, Quick update on this issue. I think the search index is looking for the packages with "IsLatestSemVer2" value 1 in the database. After updating the database we can see all packages in the gallery. Now we have one more issue, We are not able to download packages from visual studio. We can see packages in nuget gallery and can download them. I update the nuget.config file with the correct nuget gallery URL. We get 404 not found error. We are using VS 2019.

**Comment by agr** [comment]
Hi, to clarify: are you able to see the list of packages in the NuGet Package manager window in VS?
What happens if you run `nuget restore` (download nuget.exe: https://www.nuget.org/downloads) in your solution directory?
What source URL did you specify in your nuget.config? What happens if you run `nuget install <some package name> -source https://localhost/api/v2`? Did you try specifying the package source in VS settings (Tools -> Options -> NuGet package manager -> Package sources)?
What happens if you update your .csproj or packages.config file with a text editor to include a package from your feed and try to build? Anything interesting in the build logs?
Do you have any SSL errors using HTTPS on localhost?

**Comment by tharunr184** [comment]
Hi, I am able to see packages in Nuget package manager in VS. When I build project, while restoring missing packages, Nuget is not able to restore some packages. I did all of the things that you mentioned. It's only some packages that nuget is not able to restore. When I ran nuget.exe restore path/to.sln I get 404 not found for some packages. I can see those packages in the custom gallery and I can see them when I click manage packages for the solution in VS. I looked into the Database and the only difference I can see is the version and normalized version are different for these packages that Nuget is not able to restore. Please let me know if you need more information.

**Comment by agr** [comment]
Please, share the output of the `nuget.exe` that you tried.

Does restore fail for any package on your instance of Gallery or only for some of them? Are those packages that fail available through the web site? Are they present in file system (under `App_data\files\packages`)?

Is your project is using [packages.config](https://docs.microsoft.com/en-us/nuget/reference/packages-config) or [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)?

**Comment by tharunr184** [comment]
Hi, I modified the URL for obvious reasons. Here is the output 
NuGet Version: 4.9.4.5839
Feeds used:
  https://mydomain/api/v2/

Installing package 'odp.net.x64s' to 'D:\'.
  GET https://mydomain/api/v2/FindPackagesById()?id='odp.net.x64s'&semVerLevel=2.0.0
  OK https://mydomain/api/v2/FindPackagesById()?id='odp.net.x64s'&semVerLevel=2.0.0 13ms


Attempting to gather dependency information for package 'odp.net.x64s.2.112.3' with respect to project 'D:\', targeting 'Any,Version=v0.0'
Package odp.net.x64s from source https://mydomain/api/v2/ gathered from cache.
Total number of results gathered : 1
Gathering dependency information took 34.51 ms
Summary of time taken to gather dependencies per source :
Attempting to resolve dependencies for package 'odp.net.x64s.2.112.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'odp.net.x64s.2.112.3'
Resolved actions to install package 'odp.net.x64s.2.112.3'
Retrieving package 'odp.net.x64s 2.112.3' from 'https://mydomain/api/v2/'.
  GET https://mydomain/api/v2/package/odp.net.x64s/2.112.3
  NotFound https://mydomain/api/v2/package/odp.net.x64s/2.112.3 14ms
WARNING: Install failed. Rolling back...
Executing nuget actions took 75.33 ms
NuGet.Protocol.Core.Types.FatalProtocolException: Package 'odp.net.x64s.2.112.3' is not found on source 'https://mydomain/api/v2/'.
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcher.<>c__DisplayClass0_1.<<GetPackagesAsync>b__4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackagePreFetcherResult.<EnsureResultAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.PackagePreFetcherResult.<GetResultAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()

Yes, The packages are in the gallery and I can verify the packages exists in the App_Data\files\packages folder. My project is using packages.config 

Let me know if you have any questions or need more information.
Thanks

**Comment by agr** [comment]
I presume that specific version of the package (2.112.3) does exist on your instance of Gallery. You said earlier that you can download packages from the web site, what download URL is generated on the package page? Is it different from https://mydomain/api/v2/package/odp.net.x64s/2.112.3 that you see in nuget.exe output?

One thing you can try is: log in as admin to your Gallery instance, go to your `odp.net.x64s` package page (https://localhost/packages/odp.net.x64s/ I suppose) and click the "Reflow package" link there (it will only be available if your account have admin permissions). That should fix the package metadata in DB if there are any issues. After that, try installing that package again (`nuget install odp.net.x64s -source https://localhost/api/v2`). If that helps, then continue reflowing failing packages. Let me know the outcome anyways, I'll try to figure out something else if that doesn't work.

**Comment by tharunr184** [comment]
Hi, The download URL is same "https://mydomain/api/v2/package/odp.net.x64s/2.112.3 ". I am a nuget admin and I do not see "Reflow package" in the link or any other package. I am owner of all packages. I added my "Key" to the UserRoles table in database to get admin access. The issue still persists. Let me know if you need more information.
Thanks

**Comment by tharunr184** [comment]
Hey, Quick update. I can see "Reflow package". When I click it, I got an error "An error occurred while reflowing the package. Value cannot be null. Parameter name: stream "

**Comment by tharunr184** [comment]
Hello again,
When I try to download the package, I am not able to download it. I get 404 error. This is a test env and where we upgraded our Nuget Gallery. I can download the same package from the old version of Nuget Gallery. There are some packages where I am not able to download old versions of packages. These versions are probably 6-7 years old. Do you think the latest version of nuget gallery will not support these old version of packages?

**Comment by agr** [comment]
That `Value cannot be null. Parameter name: stream` error while reflowing happens when Gallery can't find the package on disk. Either the expected file is not present in `App_data\Files\packages` or `Gallery.FileStorageDirectory` setting in web.config points to some other location.

The age of the package shouldn't be the issue here, Gallery does not look inside the package when restore happens.

**Comment by tharunr184** [comment]
Hello,

Yes, you are correct. The Gallery is not able to find the package. But the package exists on the disk. After deleting the version of the package and re uploading the same version of package fixed the issue. Before deleting I took backup of package from the disk and re uploaded same package after deleting it from gallery. Not sure what the issue here is? 

Let me know if you need more information or have any questions.

**Comment by agr** [comment]
If you want to get to the root of the issue, I can suggest using [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to check what exact path Gallery tries to use when package restore is attempted and what error happens (if any).
