### ISSUE TITLE
"Could not create SSL/TLS secure channel" error in Visual Studio

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7705]
### Describe the bug
Some Visual Studio customers are reporting the following error:

```
Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
The request was aborted: Could not create SSL/TLS secure channel.
```

The NuGet team is actively investigating this problem. At this time, the issue's root cause is unknown. See: https://developercommunity.visualstudio.com/content/problem/815971/unable-to-browse-nuget-packages-1.html

### Workaround

Some customers have reported that disabling TLS 1.3 has resolved their issues:

```ps1
New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server' -Force | Out-Null
	
New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
	
New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server' -name 'DisabledByDefault' -value 1 -PropertyType 'DWord' -Force | Out-Null
	
New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client' -Force | Out-Null
	
New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client' -name 'Enabled' -value '0' -PropertyType 'DWord' -Force | Out-Null
	
New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client' -name 'DisabledByDefault' -value 1 -PropertyType 'DWord' -Force | Out-Null
Write-Host 'TLS 1.3 has been disabled.'
```

You may also need to change your .NET Framework default TLS version:

```ps1
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32
```

**Comment by niranjankala** [comment]
The fix is working for me. executing these commands made the NuGet working again in Visual Studio.

**Comment by dannyjdev** [comment]
I was able to create a VM on Azure that reproduce the problem, these are the things that I learned/noticed.

I started with the 1903 Windows version on the VM and upgrade it to Windows 1909 which seems to be the one that has the issue. The workaround here mentions that we need to set `Enabled` to `0 `and `DisabledByDefault `to `1`, something interesting is that after I updated
the Windows version I couldn't see any of those registries (HKLM:\...\Protocols\TLS 1.3\Server or HKLM:\...\Protocols\TLS 1.3\Client) on the VM and everything worked fine.

After that I created those registries manually using the opposite values `Enabled` to `1` and `DisabledByDefault` to `0` for each registry and when I tried to perform a search on the VS package manager I could reproduce the error everyone is getting.

I downloaded 3 different versions of Visual Studio (**Community 2019 16.3.9, Community 2019 Preview 16.4.0 Preview 5.0, and Professional 2019 Preview 16.4.0 Preview 5.0**) everyone facing the same issue for invalid registries. This issue can be seen on NuGet PM UI and VS Extensions.

As the workaround above mentions, disabling TLS 1.3 resolved the issue.

**Comment by dannyjdev** [comment]
We think that we have already fixed the issue on our side, in case someone else is having the same problem please reach out to our support email (support@nuget.org) or create an issue on our GitHub repository (https://github.com/NuGet/NuGetGallery/issues), our team should be able to provide help.

**Comment by vatsan-madhavan** [comment]
@dannyjdev @rladuca and I have hit this issue a couple of times in the last week, and we just heard a report from one of our testers that they hit the issue too. The workaround is has been effective (great!), but is there a programmatic safeguard/prevention that we can put in that would sidestep the problem from happening in the first place?

**Comment by bmomartins** [comment]
Worked for me, thanks!
Issue encountered when using `Install-GraphViz` cmdlet.

**Comment by stevenlupo** [comment]
If this does not work, you have to make sure you have the TLS 1.2 registry keys present. To add them, [see this](https://github.com/NuGet/NuGetGallery/issues/8176#issuecomment-683923724).

This was the problem I had. It won't default to TLS 1.2 even if you tell it not to use TLS 1.3.

**Comment by hieunm22** [comment]
I still have problem when running dotnet build to build my app
I'm using **Ubuntu 18.04 LTS**, how to fix it? 
thanks

**Comment by E66666666** [comment]
This issue seems to have arised again. In November 2020, I was able to publish a self-contained, single-file C# application (using the then-latest available VS2019) without issues. Today I ran into this issue (VS2019 16.8.6) trying to publish it again, using the same settings.

Windows 10 1809 (Company laptop)
Visual Studio 2019 16.8.6

Running the workaround commands fixed the issue for me, but still odd it stopped working randomly.

**Comment by ahwm** [comment]
Having this issue on Windows Server 2012 R2 with VS 2019 16.10. Workarounds had no effect. Updated to latest 16.11 and still nothing.

Running `dotnet add` runs successfully but the package manager and nuget CLI 5.11.0.10 exhibit this behavior and will not work.

**Comment by FyiurAmron** [comment]
Problem was appearing for me as well, being too dependent on default OS settings instead of negotiating properly is a big no-no IMVHO.

Workarounds work, but hey, that means disabling TLS 1.3 for my _entire_ OS _sigh_.

**Comment by 1415rr** [comment]
works for me .  I guess that was the ".net v4" setings on regedit. 
tks a lot!!!!

**Comment by rqueizan** [comment]
I think I have the same problem, but the solution did not work for me.

Using:
Microsoft Visual Studio Enterprise 2022
Version 17.4.0 Preview 3.0
VisualStudio.17.Preview/17.4.0-pre.3.0+33006.217
Microsoft .NET Framework
Version 4.8.04161

Error message:
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.

**Comment by rqueizan** [comment]
> I think I have the same problem, but the solution did not work for me.
> 
> Using: Microsoft Visual Studio Enterprise 2022 Version 17.4.0 Preview 3.0 VisualStudio.17.Preview/17.4.0-pre.3.0+33006.217 Microsoft .NET Framework Version 4.8.04161
> 
> Error message: [nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json. An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. The remote certificate is invalid according to the validation procedure.
> 
> Edge browser: ![image](https://user-images.githubusercontent.com/18214796/195692198-7981453a-449a-4a39-9a8f-0a6b50c75d26.png)
> 
> WinMTR 0.92 64bits: ![image](https://user-images.githubusercontent.com/18214796/195695031-830d1e37-40f5-4854-9ca2-d49724c7c177.png)

Resolved!
devenv.exe require access to oneocsp.microsoft.com

**Comment by rqueizan** [comment]
> @rqueizan How did you resolve this? could you provide some steps?
> 
> I am running into this with the same preview version you have. _Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 3.0_

I have extremely restricted Internet access for all applications.
When I gave Visual Studio (devenv.exe) access to the oneocsp.microsoft.com server, it automatically resolved the error and listed all the packages for me.

**Comment by SenthilSelvaraju** [comment]
this seem to be happening specific to the Preview version of VS 2022, and I tried with both _Version 17.4.0 Preview 3.0_ & _Version 17.4.0 Preview 4.0_.

However VS 2019 does not have this issue, in the same PC & same network. I am wondering this is a defect specific to the VS 2022 Preview builds.

Does anyone know who would be the right person to bring this into their attention?
